# Header
menu:
  Магазин: http://hao-cha.ru/
  Архив: /archives
rss: /atom.xml

# Content
excerpt_link: Читать дальше >> 
fancybox: true

# Miscellaneous
google_analytics:
favicon: source/images/favicon.png